version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: habr_spring_security_6_db
    environment:
      POSTGRES_DB: habr_spring_security_6
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
